include: package:pedantic/analysis_options.1.9.0.yaml

strong-mode:
  implicit-casts: false
  implicit-dynamic: false

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false