include: package:flutter_lints/flutter.yaml

strong-mode:
  implicit-casts: false
  implicit-dynamic: false

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    use_key_in_widget_constructors: false
